// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import v1alpha1 "github.com/kyma-project/kyma/components/event-bus/api/push/eventing.kyma-project.io/v1alpha1"

// SubscriptionInterface is an autogenerated mock type for the SubscriptionInterface type
type SubscriptionInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *SubscriptionInterface) Create(_a0 *v1alpha1.Subscription) (*v1alpha1.Subscription, error) {
	ret := _m.Called(_a0)

	var r0 *v1alpha1.Subscription
	if rf, ok := ret.Get(0).(func(*v1alpha1.Subscription) *v1alpha1.Subscription); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Subscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1alpha1.Subscription) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
