// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import registration "github.com/kyma-incubator/hack-showcase/github-connector/internal/registration"

// PayloadBuilder is an autogenerated mock type for the PayloadBuilder type
type PayloadBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *PayloadBuilder) Build() (registration.ServiceDetails, error) {
	ret := _m.Called()

	var r0 registration.ServiceDetails
	if rf, ok := ret.Get(0).(func() registration.ServiceDetails); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(registration.ServiceDetails)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApplicationRegistryURL provides a mock function with given fields:
func (_m *PayloadBuilder) GetApplicationRegistryURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
