// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import v1alpha1 "github.com/kyma-project/kyma/components/event-bus/generated/push/clientset/versioned/typed/eventing.kyma-project.io/v1alpha1"

// EventbusClient is an autogenerated mock type for the EventbusClient type
type EventbusClient struct {
	mock.Mock
}

// Subscriptions provides a mock function with given fields: _a0
func (_m *EventbusClient) Subscriptions(_a0 string) v1alpha1.SubscriptionInterface {
	ret := _m.Called(_a0)

	var r0 v1alpha1.SubscriptionInterface
	if rf, ok := ret.Get(0).(func(string) v1alpha1.SubscriptionInterface); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.SubscriptionInterface)
		}
	}

	return r0
}
