// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import v1beta1 "github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1"

// KubelessClient is an autogenerated mock type for the KubelessClient type
type KubelessClient struct {
	mock.Mock
}

// Functions provides a mock function with given fields: _a0
func (_m *KubelessClient) Functions(_a0 string) v1beta1.FunctionInterface {
	ret := _m.Called(_a0)

	var r0 v1beta1.FunctionInterface
	if rf, ok := ret.Get(0).(func(string) v1beta1.FunctionInterface); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.FunctionInterface)
		}
	}

	return r0
}
